{{- $root := . -}}
{{ if .Values.executor.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "zuul.fullname" . }}-executor
  labels:
{{- include "zuul.executor.labels" . | indent 4 }}
  annotations:
{{- include "zuul.executor.annotations" . | indent 4 }}
spec:
  serviceName: {{ include "zuul.fullname" . }}-executor
  replicas: {{ .Values.executor.replicas }}
  selector:
    matchLabels:
{{- include "zuul.executor.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{- include "zuul.executor.labels" . | indent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
{{- include "zuul.executor.annotations" . | indent 8 }}
    spec:
      containers:
      - name: executor
        image: {{ $root.Values.executor.image | default "quay.io/zuul-ci/zuul-executor:latest" }}
        ports:
        - name: logs
          containerPort: 7900
        securityContext:
          privileged: true
        volumeMounts:
        - name: zuul-config
          mountPath: /etc/zuul
        {{- range $secret, $secret_values := $root.Values.secrets -}}
        {{- if $secret_values.mount }}
        - name: {{ $secret }}
          {{- $secret_values.mount | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- range $secret, $secret_values := $root.Values.executor.secrets -}}
        {{- if $secret_values.mount }}
        - name: {{ $secret }}
          {{- $secret_values.mount | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
      volumes:
      - name: zuul-config
        secret:
          secretName: {{ include "zuul.fullname" . }}
      {{- range $secret, $secret_values := $root.Values.secrets -}}
      {{- if $secret_values.mount }}
      - name: {{ $secret }}
        secret:
          secretName: {{ $secret }}
          {{- if $secret_values.volume }}
          {{- $secret_values.volume | toYaml | nindent 10 }}
          {{- end -}}
      {{- end -}}
      {{- end -}}
      {{- range $secret, $secret_values := $root.Values.executor.secrets -}}
      {{- if $secret_values.mount }}
      - name: {{ $secret }}
        secret:
          secretName: {{ $secret }}
          {{- if $secret_values.volume }}
          {{- $secret_values.volume | toYaml | nindent 10 }}
          {{- end -}}
      {{- end -}}
      {{- end -}}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
{{ end }}
