{{- $root := . -}}
{{ if .Values.builder.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "nodepool.fullname" . }}-builder
  labels:
{{- include "nodepool.builder.labels" . | indent 4 }}
  annotations:
{{- include "nodepool.builder.annotations" . | indent 4 }}
spec:
  replicas: {{ .Values.builder.replicas }}
  serviceName: nodepool-builder
  selector:
    matchLabels:
{{- include "nodepool.builder.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{- include "nodepool.builder.labels" . | indent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
{{- include "nodepool.builder.annotations" . | indent 8 }}
    spec:
      containers:
      - name: builder
        image: {{ $root.Values.builder.image | default "quay.io/zuul-ci/nodepool-builder:latest" }}
        env:
        - name: OS_CLIENT_CONFIG_FILE
          value: /etc/nodepool/clouds.yaml
        securityContext:
          privileged: true
        volumeMounts:
        - name: nodepool-config
          mountPath: /etc/nodepool
        - name: nodepool-logs
          mountPath: /var/log/nodepool
        - name: {{ include "nodepool.fullname" . }}-images-dir
          mountPath: {{ index .Values.config "images-dir" }}
        - name: dev
          mountPath: /dev
        {{- range $secret, $secret_values := $root.Values.secrets -}}
        {{- if $secret_values.mount }}
        - name: {{ $secret }}
          {{- $secret_values.mount | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- range $secret, $secret_values := $root.Values.builder.secrets -}}
        {{- if $secret_values.mount }}
        - name: {{ $secret }}
          {{- $secret_values.mount | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
      serviceAccount: nodepool
      serviceAccountName: nodepool
      volumes:
      - name: nodepool-config
        secret:
          secretName: {{ (empty .Values.config.secret) | ternary (include "nodepool.fullname" .) .Values.config.secret  }}
      - name: nodepool-logs
        emptyDir: {}
      - name: dev
        hostPath:
          path: /dev
      {{- range $secret, $secret_values := $root.Values.secrets -}}
      {{- if $secret_values.mount }}
      - name: {{ $secret }}
        secret:
          secretName: {{ $secret }}
          {{- if $secret_values.volume }}
          {{- $secret_values.volume | toYaml | nindent 10 }}
          {{- end -}}
      {{- end -}}
      {{- end -}}
      {{- range $secret, $secret_values := $root.Values.builder.secrets -}}
      {{- if $secret_values.mount }}
      - name: {{ $secret }}
        secret:
          secretName: {{ $secret }}
          {{- if $secret_values.volume }}
          {{- $secret_values.volume | toYaml | nindent 10 }}
          {{- end -}}
      {{- end -}}
      {{- end -}}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "nodepool.fullname" . }}-images-dir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 80G
{{ end }}
