{{- $root := . -}}
{{ if .Values.merger.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "zuul.fullname" . }}-merger
  labels:
{{- include "zuul.merger.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.merger.replicas }}
  selector:
    matchLabels:
{{- include "zuul.merger.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{- include "zuul.merger.labels" . | indent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: merger
        image: zuul/zuul-merger:latest
        volumeMounts:
        - name: zuul-config
          mountPath: /etc/zuul
        {{- range $secret, $secret_values := $root.Values.secrets -}}
        {{- if $secret_values.mount }}
        - name: {{ $secret }}
          {{- $secret_values.mount | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- range $secret, $secret_values := $root.Values.merger.secrets -}}
        {{- if $secret_values.mount }}
        - name: {{ $secret }}
          {{- $secret_values.mount | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
      volumes:
      - name: zuul-config
        secret:
          secretName: {{ include "zuul.fullname" . }}
          defaultMode: 256
      {{- range $secret, $secret_values := $root.Values.secrets -}}
      {{- if $secret_values.mount }}
      - name: {{ $secret }}
        secret:
          secretName: {{ $secret }}
          {{- if $secret_values.volume }}
          {{- $secret_values.volume | toYaml | nindent 10 }}
          {{- end -}}
      {{- end -}}
      {{- end -}}
      {{- range $secret, $secret_values := $root.Values.merger.secrets -}}
      {{- if $secret_values.mount }}
      - name: {{ $secret }}
        secret:
          secretName: {{ $secret }}
          {{- if $secret_values.volume }}
          {{- $secret_values.volume | toYaml | nindent 10 }}
          {{- end -}}
      {{- end -}}
      {{- end -}}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
{{ end }}
