{{- $root := . -}}
{{ if .Values.web.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "zuul.fullname" . }}-web
  labels:
{{- include "zuul.web.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
{{- include "zuul.web.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{- include "zuul.web.labels" . | indent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
      {{- range $cont_name, $cont := $root.Values.web.sidecar }}
      - name: {{$cont_name}}
        {{- $cont | toYaml | nindent 8 }}
      {{- end }}
      - name: web
        image: {{ $root.Values.web.image | default "quay.io/zuul-ci/zuul-web:latest" }}
        ports:
        - name: zuul-web
          containerPort: {{ .Values.web.port }}
        volumeMounts:
        - name: zuul-config
          mountPath: /etc/zuul
        {{- range $secret, $secret_values := $root.Values.secrets -}}
        {{- if $secret_values.mount }}
        - name: {{ $secret }}
          {{- $secret_values.mount | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- range $secret, $secret_values := $root.Values.merger.secrets -}}
        {{- if $secret_values.mount }}
        - name: {{ $secret }}
          {{- $secret_values.mount | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
      volumes:
      - name: zuul-config
        secret:
          secretName: {{ include "zuul.fullname" . }}
          defaultMode: 256
      {{- range $secret, $secret_values := $root.Values.secrets -}}
      {{- if $secret_values.mount }}
      - name: {{ $secret }}
        secret:
          secretName: {{ $secret }}
          {{- if $secret_values.volume }}
          {{- $secret_values.volume | toYaml | nindent 10 }}
          {{- end -}}
      {{- end -}}
      {{- end -}}
      {{- range $secret, $secret_values := $root.Values.merger.secrets -}}
      {{- if $secret_values.mount }}
      - name: {{ $secret }}
        secret:
          secretName: {{ $secret }}
          {{- if $secret_values.volume }}
          {{- $secret_values.volume | toYaml | nindent 10 }}
          {{- end -}}
      {{- end -}}
      {{- end -}}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
{{ end }}
