---
{{ if and .Values.web.ingress.enabled .Values.web.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "zuul.fullname" . }}-web
  labels:
{{- .Values.web.ingress.labels | toYaml | nindent 4 }}
  annotations:
{{- .Values.web.ingress.annotations | toYaml | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.web.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "zuul.fullname" . }}-web
          servicePort: {{ .Values.web.port }}
        path: /
  tls:
  - hosts:
    - {{ .Values.web.ingress.host }}
    secretName: {{ include "zuul.fullname" . }}-web-certs
{{ end }}
