---
{{ if and .Values.web.ingress.enabled .Values.web.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "zuul.fullname" . }}-web
  labels:
{{- .Values.web.ingress.labels | toYaml | nindent 4 }}
  annotations:
{{- .Values.web.ingress.annotations | toYaml | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.web.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "zuul.fullname" . }}-web
            port:
              number: {{ .Values.web.port }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.web.ingress.host }}
    secretName: {{ include "zuul.fullname" . }}-web-certs
{{ end }}
