---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "zuul.fullname" . }}
  labels:
{{- include "zuul.common.labels" . | indent 4 }}
stringData:
  zuul.conf: |
    [database]
    dburi={{ .Values.database.port }}

    [gearman]
    server={{ include "zuul.fullname" . }}-gearman
    port={{ .Values.scheduler.gearman.port }}

    [zookeeper]
    hosts={{ .Values.zookeeper.hosts }}

    [gearman_server]
    start=true
    port={{ .Values.scheduler.gearman.port }}

    [web]
    listen_address=0.0.0.0
    root=https://{{ .Values.web.host }}
    port={{ .Values.web.port }}

    [scheduler]
    tenant_config={{ .Values.scheduler.tenantConfigPath }}

    [executor]
    disk_limit_per_job={{ .Values.executor.diskLimitPerJob }}
    private_key_file={{ .Values.executor.private_key_file }}
    {{ range $connection, $options := .Values.connections }}

    [connection {{ $connection }}]
    {{ range $key, $value := $options }}
    {{ $key }} = {{ $value }}
    {{ end }}
    {{ end }}
  main.yaml: |
{{ toYaml .Values.tenantConfig | indent 4 }}
{{ if .Values.extraFiles }}
{{ (toYaml .Values.extraFiles | indent 2) }}
{{ end }}
