---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "zuul.fullname" . }}
  labels:
{{- include "zuul.common.labels" . | indent 4 }}
stringData:
  zuul.conf: |
    [database]
    dburi={{ .Values.database.uri }}

    [keystore]
    password={{ .Values.keystore.password }}

    [gearman]
    server={{ include "zuul.fullname" . }}-gearman
    port={{ .Values.scheduler.gearman.port }}

    [zookeeper]
    hosts={{ join "," .Values.zookeeper.hosts }}
    {{- if .Values.zookeeper.certs_path }}
    tls_cert={{ .Values.zookeeper.certs_path }}/tls.crt
    tls_key={{ .Values.zookeeper.certs_path }}/tls.key
    tls_ca={{ .Values.zookeeper.certs_path }}/ca.crt
    {{- end }}

    [gearman_server]
    start=true
    port={{ .Values.scheduler.gearman.port }}

    [web]
    listen_address=0.0.0.0
    {{- if .Values.web.ingress.enabled }}
    root=https://{{ .Values.web.ingress.host }}
    {{- end }}
    port={{ .Values.web.port }}

    [webclient]
    url = http://zuul-system-web
    verify_ssl = false

    [scheduler]
    tenant_config={{ .Values.scheduler.tenantConfigPath }}

    [executor]
    {{- if .Values.executor.trustedRoPaths }}
    trusted_ro_paths={{ .Values.executor.trustedRoPaths }}
    {{- end }}
    {{- if .Values.executor.untrustedRoPaths }}
    untrusted_ro_paths={{ .Values.executor.untrustedRoPaths }}
    {{- end }}
    disk_limit_per_job={{ .Values.executor.diskLimitPerJob }}
    private_key_file={{ .Values.executor.private_key_file }}
    {{ range $connection, $options := .Values.connections }}

    [connection {{ $connection }}]
    {{- range $key, $value := $options }}
    {{ $key }} = {{ $value }}
    {{- end }}
    {{- end }}

    {{- range $authenticator, $options := .Values.authenticators }}

    [auth {{ $authenticator }}]
    {{- range $key, $value := $options }}
    {{ $key }} = {{ $value }}
    {{- end }}
    {{- end }}
  main.yaml: |
{{ toYaml .Values.tenantConfig | indent 4 }}
{{ if .Values.extraFiles }}
{{ (toYaml .Values.extraFiles | indent 2) }}
{{ end }}
