{{- $root := . -}}
{{ if .Values.scheduler.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "zuul.fullname" . }}-scheduler
  labels:
{{- include "zuul.scheduler.labels" . | indent 4 }}
  annotations:
{{- include "zuul.scheduler.annotations" . | indent 4 }}
spec:
  replicas: 1
  serviceName: zuul-scheduler
  selector:
    matchLabels:
{{- include "zuul.scheduler.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{- include "zuul.scheduler.labels" . | indent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
{{- include "zuul.scheduler.annotations" . | indent 8 }}
    spec:
      containers:
      - name: launcher
        image: {{ $root.Values.scheduler.image | default "quay.io/zuul-ci/zuul-scheduler:latest" }}
        ports:
        - name: gearman
          containerPort: {{ .Values.scheduler.gearman.port }}
        volumeMounts:
        - name: zuul-config
          mountPath: /etc/zuul
        - name: {{ include "zuul.fullname" . }}-scheduler
          mountPath: /var/lib/zuul
{{- if .Values.scheduler.tenantConfigSecret }}
        - name: zuul-tenant-config
          mountPath: /etc/zuul/tenant
{{- end }}
        {{- range $secret, $secret_values := $root.Values.secrets -}}
        {{- if $secret_values.mount }}
        - name: {{ $secret }}
          {{- $secret_values.mount | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- range $secret, $secret_values := $root.Values.scheduler.secrets -}}
        {{- if $secret_values.mount }}
        - name: {{ $secret }}
          {{- $secret_values.mount | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
      volumes:
      - name: zuul-config
        secret:
          secretName: {{ include "zuul.fullname" . }}
          defaultMode: 256
{{- if .Values.scheduler.tenantConfigSecret }}
      - name: zuul-tenant-config
        secret:
          secretName: {{ .Values.scheduler.tenantConfigSecret }}
{{- end }}
      {{- range $vol, $vol_values := $root.Values.volumes }}
      - name: {{ $vol }}
        {{- required "Volume source info is required" $vol_values.source | toYaml | nindent 8 }}
      {{- end }}
      {{- range $secret, $secret_values := $root.Values.secrets -}}
      {{- if $secret_values.mount }}
      - name: {{ $secret }}
        secret:
          secretName: {{ $secret }}
          {{- if $secret_values.volume }}
          {{- $secret_values.volume | toYaml | nindent 10 }}
          {{- end -}}
      {{- end -}}
      {{- end -}}
      {{- range $secret, $secret_values := $root.Values.scheduler.secrets -}}
      {{- if $secret_values.mount }}
      - name: {{ $secret }}
        secret:
          secretName: {{ $secret }}
          {{- if $secret_values.volume }}
          {{- $secret_values.volume | toYaml | nindent 10 }}
          {{- end -}}
      {{- end -}}
      {{- end -}}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "zuul.fullname" . }}-scheduler
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 80Gi
{{ end }}
